In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
sns.set();

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

In [3]:
df = pd.read_csv('city_united.csv')
df

,UA_Name,UA_Country,UA_Continent,Housing,Cost of Living,Startups,Venture Capital,Travel Connectivity,Commute,Business Freedom,...,Healthcare,Education,Environmental Quality,Economy,Taxation,Internet Access,Leisure & Culture,Tolerance,Outdoors,Quality of Life Index
0,Adelaide,Australia,Oceania,6.3095,4.692,3.1365,2.640,1.7765,5.33625,9.399667,...,7.936667,5.1420,8.33075,6.0695,4.5885,4.3410,4.3285,7.8220,5.5310,200.03
1,Raleigh,North Carolina,North America,6.1285,5.610,5.4970,5.157,1.7570,4.78425,8.671000,...,6.677333,7.1165,8.58375,6.5145,4.0620,7.9515,6.6130,7.5620,3.3905,197.30
2,Zurich,Switzerland,Europe,1.4730,1.000,6.2035,3.872,7.7335,5.83950,8.888000,...,7.670333,7.2875,8.64300,6.5520,6.4285,7.2675,4.9655,8.7845,5.4010,194.41
3,Wellington,New Zealand,Oceania,5.1345,5.161,2.4715,1.753,0.8525,6.03975,10.000000,...,8.078333,4.7560,9.60925,5.5055,5.9315,5.1745,4.5990,8.1160,6.3970,193.89
4,Charlotte,North Carolina,North America,5.5490,4.987,6.2480,2.878,3.6790,4.13400,8.671000,...,6.432333,3.6245,8.00925,6.5145,4.0620,6.3870,5.6060,6.7895,1.3115,193.30
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
182,Delhi,India,Asia,9.7520,9.869,9.8285,9.099,5.6420,3.71225,3.618000,...,3.712667,0.5120,2.20300,5.5565,3.4145,3.5880,5.6830,3.1160,1.1785,69.56
183,Jakarta,Indonesia,Asia,8.6710,8.471,5.6495,6.437,2.4885,3.64000,4.028667,...,4.184000,1.0275,2.48575,4.6575,6.2660,4.4990,8.1460,2.0665,7.2020,68.46
184,Lagos,Nigeria,Africa,7.7670,9.098,6.4335,2.510,1.7480,3.56475,3.255667,...,2.862333,0.0000,1.90725,5.0610,6.2155,1.6340,1.3585,1.4060,3.8245,50.72
185,Manila,Philippines,Asia,8.5955,8.752,4.8050,3.547,2.6345,3.71300,4.592333,...,4.297667,0.0000,1.68300,5.0065,4.3030,4.6080,7.5840,5.5030,4.8255,41.88
186,Tehran,Iran,Asia,8.3030,9.544,4.3865,0.000,3.1750,3.79950,4.342667,...,5.312333,0.5100,2.94250,3.9435,4.0525,1.5760,6.5210,4.2225,5.5000,35.22

In [4]:
df.info() #пропусков нет

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 187 entries, 0 to 186
Data columns (total 21 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   UA_Name                187 non-null    object
 1   UA_Country             187 non-null    object
 2   UA_Continent           187 non-null    object
 3   Housing                187 non-null    float64
 4   Cost of Living         187 non-null    float64
 5   Startups               187 non-null    float64
 6   Venture Capital        187 non-null    float64
 7   Travel Connectivity    187 non-null    float64
 8   Commute                187 non-null    float64
 9   Business Freedom       187 non-null    float64
 10  Safety                 187 non-null    float64
 11  Healthcare             187 non-null    float64
 12  Education              187 non-null    float64
 13  Environmental Quality  187 non-null    float64
 14  Economy                187 non-null    float64
 15  Taxation               187 non-null    float64
 16  Internet Access        187 non-null    float64
 17  Leisure & Culture      187 non-null    float64
 18  Tolerance              187 non-null    float64
 19  Outdoors               187 non-null    float64
 20  Quality of Life Index  187 non-null    float64
dtypes: float64(18), object(3)
memory usage: 30.8+ KB

In [5]:
#Создаем x и y
x = df.drop(['UA_Name', 'Quality of Life Index'], axis=1)
y = df['Quality of Life Index']

In [6]:
#Сделаем обработку категориальных переменных
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
x['UA_Country'] = encoder.fit_transform(x['UA_Country'])
x['UA_Continent'] = encoder.fit_transform(x['UA_Continent'])

In [7]:
train_x, test_x, train_y, test_y = train_test_split(x, y, test_size=0.33, random_state=42)

In [8]:
import math 
from sklearn.metrics import r2_score

In [9]:
#Построим регрессию исходной модели
reg = LinearRegression().fit(train_x, train_y)
predictions = reg.predict(test_x)
Ri = r2_score(test_y, predictions)
MSE = mean_squared_error(test_y, predictions)
print("Исходная модель: Rквадрат:", Ri, "MSE:", MSE)

Исходная модель: Rквадрат: 0.7174188146827849 MSE: 355.2561028672303

In [10]:
#Отберем признаки на основе пермутационной важности
import eli5
from eli5.sklearn import PermutationImportance

In [11]:
perm = PermutationImportance(reg, random_state=42).fit(test_x, test_y)

In [12]:
eli5.show_weights(perm, feature_names=list(test_x.columns))

In [13]:
column1 = ['Venture Capital', 'Business Freedom', 'Education',
       'Environmental Quality', 'Economy']

In [14]:
train_x_new = train_x[column1]
test_x_new = test_x[column1]
reg = LinearRegression().fit(train_x_new, train_y)
predictions = reg.predict(test_x_new)
Ri = r2_score(test_y, predictions)
MSE = mean_squared_error(test_y, predictions)
print("Новая модель: Rквадрат:", Ri, "MSE:", MSE)

Новая модель: Rквадрат: 0.8192920624810537 MSE: 227.18284505774855

Модель стала лучше

In [15]:
#Отберем признаки на основе f-статистики
from sklearn.feature_selection import f_regression, SelectKBest
f_statistic, p_values = f_regression(train_x, train_y)
sekector = SelectKBest(f_regression, k=5)
sekector.fit_transform(train_x, train_y)

array([[ 5.522     ,  8.966     ,  8.269     ,  8.17575   ,  7.9255    ],
       [ 5.595     ,  8.671     ,  6.75566667,  7.2505    ,  4.7755    ],
       [ 6.301     ,  7.43866667,  6.75866667,  3.672     ,  7.5055    ],
       [ 5.049     ,  8.992     ,  8.519     ,  4.363     ,  6.677     ],
       [ 3.94      ,  8.992     ,  8.018     ,  5.54775   ,  6.573     ],
       [ 6.108     ,  8.671     ,  6.346     ,  7.1095    ,  5.299     ],
       [ 5.814     ,  8.992     ,  8.29366667,  5.7385    ,  6.421     ],
       [ 1.        ,  9.36      ,  8.079     ,  8.62375   ,  9.565     ],
       [ 4.477     ,  8.877     ,  8.15833333,  4.591     ,  6.481     ],
       [ 9.869     ,  3.618     ,  3.71266667,  2.203     ,  3.116     ],
       [ 9.125     ,  5.94833333,  6.91433333,  2.936     ,  4.4855    ],
       [ 5.355     ,  8.671     ,  6.28166667,  7.03075   ,  6.7895    ],
       [ 5.882     ,  8.966     ,  7.75566667,  5.67475   ,  6.659     ],
       [ 9.765     ,  7.86333333,  5.05233333,  3.19675   ,  8.1975    ],
       [ 6.173     ,  8.671     ,  7.007     ,  9.524     ,  7.9005    ],
       [ 4.128     ,  9.39966667,  8.03366667,  7.81675   ,  7.0325    ],
       [ 5.759     ,  8.671     ,  5.63533333,  5.5565    ,  7.275     ],
       [ 4.987     ,  8.671     ,  6.43233333,  8.00925   ,  6.7895    ],
       [ 5.359     ,  8.671     ,  6.199     ,  7.12025   ,  5.6785    ],
       [ 4.36      ,  9.569     ,  8.03933333,  8.99175   ,  5.7195    ],
       [ 3.664     ,  8.08833333,  8.20766667,  4.36225   ,  5.579     ],
       [ 6.249     ,  7.11966667,  8.91633333,  5.5655    ,  7.665     ],
       [ 5.98      ,  3.173     ,  4.36333333,  4.49325   ,  3.66      ],
       [ 5.949     ,  8.671     ,  6.48833333,  6.62175   ,  7.151     ],
       [ 8.495     ,  5.60366667,  7.39366667,  3.981     ,  6.8715    ],
       [ 2.618     ,  8.671     ,  6.449     ,  6.4815    ,  8.0125    ],
       [ 9.08      ,  6.34866667,  6.30166667,  4.3475    ,  8.5555    ],
       [ 4.692     ,  9.39966667,  7.93666667,  8.33075   ,  7.822     ],
       [ 9.445     ,  4.74033333,  4.116     ,  1.        ,  9.129     ],
       [ 6.6       ,  6.169     ,  7.509     ,  3.33825   ,  7.5235    ],
       [ 5.526     ,  8.671     ,  6.08233333,  7.989     ,  4.844     ],
       [ 4.497     ,  8.671     ,  6.031     ,  6.292     ,  6.0435    ],
       [ 6.749     ,  7.67666667,  7.67166667,  8.66175   ,  8.184     ],
       [ 5.143     ,  9.07233333,  7.70733333,  6.4755    ,  7.0345    ],
       [ 2.342     ,  8.671     ,  6.10533333,  5.23375   ,  6.7125    ],
       [ 6.037     ,  8.966     ,  8.13133333,  7.3155    ,  8.622     ],
       [ 4.798     ,  9.39966667,  8.016     ,  7.8915    ,  7.0005    ],
       [10.        ,  3.618     ,  3.937     ,  2.75575   ,  3.4845    ],
       [ 8.509     ,  5.70433333,  6.854     ,  4.802     ,  4.592     ],
       [ 3.79      ,  8.671     ,  6.30966667,  7.56025   ,  8.0895    ],
       [ 3.426     ,  9.94      ,  7.98533333,  8.27225   ,  9.0955    ],
       [ 4.801     ,  6.18966667,  8.44466667,  4.458     ,  7.2195    ],
       [ 5.607     ,  9.07233333,  8.04      ,  6.48      ,  6.7115    ],
       [ 7.194     ,  5.72033333,  7.266     ,  7.3315    ,  7.9545    ],
       [ 2.867     ,  8.671     ,  6.431     ,  6.094     ,  7.774     ],
       [ 4.924     ,  8.671     ,  6.31766667,  8.4595    ,  8.1595    ],
       [ 6.074     ,  7.11966667,  8.40333333,  3.6655    ,  7.4715    ],
       [ 7.569     ,  6.21266667,  7.881     ,  7.01425   ,  8.1985    ],
       [ 5.49      ,  8.037     ,  6.392     ,  6.0355    ,  5.4265    ],
       [ 8.844     ,  4.10166667,  5.54033333,  1.41975   ,  5.9435    ],
       [ 7.822     ,  3.02133333,  6.40633333,  4.17625   ,  8.8265    ],
       [ 5.253     ,  8.671     ,  6.573     ,  7.37875   ,  5.36      ],
       [ 4.349     ,  8.08833333,  8.64166667,  6.54325   ,  6.517     ],
       [ 8.516     ,  5.68166667,  6.07533333,  3.41925   ,  8.6865    ],
       [10.        ,  5.79066667,  4.041     ,  1.1555    ,  2.65      ],
       [ 4.47      , 10.        ,  8.16266667,  8.2725    ,  7.402     ],
       [ 5.102     ,  8.671     ,  6.22033333,  7.11675   ,  7.8605    ],
       [ 6.027     ,  8.966     ,  8.01133333,  9.29225   ,  8.6295    ],
       [ 4.795     ,  8.671     ,  6.39966667,  6.87425   ,  7.39      ],
       [ 9.431     ,  6.501     ,  5.102     ,  4.4395    ,  7.3465    ],
       [ 6.728     ,  5.94966667,  7.43266667,  5.25625   ,  8.9385    ],
       [ 5.673     ,  9.07233333,  7.85133333,  7.225     ,  7.5335    ],
       [ 9.098     ,  3.25566667,  2.86233333,  1.90725   ,  1.406     ],
       [ 8.434     ,  5.70433333,  6.78133333,  4.96475   ,  3.9045    ],
       [ 5.161     , 10.        ,  8.07833333,  9.60925   ,  8.116     ],
       [ 7.329     ,  7.36333333,  5.71      ,  6.966     ,  6.884     ],
       [ 6.931     ,  8.12933333,  7.36633333,  7.8255    ,  7.8385    ],
       [ 9.244     ,  5.761     ,  6.38      ,  2.50625   ,  7.089     ],
       [ 7.823     ,  2.781     ,  5.372     ,  2.6535    ,  6.8955    ],
       [ 6.172     ,  8.671     ,  6.24633333,  6.21575   ,  8.6225    ],
       [ 5.948     ,  8.966     ,  7.395     ,  7.7215    ,  8.193     ],
       [ 5.134     ,  9.07233333,  8.00366667,  7.3755    ,  7.8685    ],
       [ 5.228     ,  8.671     ,  6.45733333,  8.32925   ,  7.404     ],
       [ 5.644     ,  8.34166667,  5.90533333,  6.23575   ,  8.0435    ],
       [ 8.794     ,  5.68166667,  6.43433333,  6.40075   ,  8.624     ],
       [ 5.242     ,  8.992     ,  8.25166667,  6.47225   ,  7.4395    ],
       [ 8.175     ,  4.617     ,  4.76366667,  3.75775   ,  7.157     ],
       [ 9.088     ,  5.61433333,  4.47      ,  2.2555    ,  2.945     ],
       [ 5.271     ,  8.966     ,  8.06366667,  7.1775    ,  7.928     ],
       [ 4.653     ,  8.83666667,  8.214     ,  8.28375   ,  8.553     ],
       [ 5.844     ,  8.671     ,  6.44966667,  7.9765    ,  5.0205    ],
       [ 7.576     ,  7.60033333,  6.33066667,  8.71775   ,  7.393     ],
       [ 8.099     ,  5.38666667,  4.763     ,  5.27475   ,  3.475     ],
       [ 8.659     ,  2.58033333,  6.52566667,  3.666     ,  7.7365    ],
       [ 5.156     ,  8.671     ,  6.51966667,  7.26725   ,  8.5395    ],
       [ 5.241     ,  8.671     ,  6.02333333,  5.81775   ,  4.062     ],
       [ 4.967     ,  9.29433333,  4.154     ,  4.53325   ,  7.152     ],
       [ 6.5       ,  6.169     ,  7.153     ,  3.80225   ,  6.268     ],
       [ 9.817     ,  4.52533333,  4.851     ,  3.6665    ,  6.827     ],
       [ 7.222     ,  5.60366667,  7.12666667,  3.37125   ,  6.019     ],
       [ 5.042     ,  8.671     ,  6.681     ,  8.362     ,  7.288     ],
       [ 3.824     ,  8.83666667,  7.90733333,  7.59725   ,  8.368     ],
       [ 4.422     ,  8.671     ,  6.48266667,  5.124     ,  5.8645    ],
       [ 6.872     ,  7.11966667,  8.88566667,  5.94225   ,  7.935     ],
       [ 8.471     ,  4.02866667,  4.184     ,  2.48575   ,  2.0665    ],
       [ 6.059     ,  8.671     ,  6.43      ,  7.3195    ,  7.0285    ],
       [ 5.284     ,  8.671     ,  5.96733333,  6.676     ,  5.784     ],
       [ 7.422     ,  8.23866667,  8.16666667,  7.03875   ,  9.5735    ],
       [ 6.728     ,  5.94966667,  7.43266667,  5.25625   ,  8.9385    ],
       [ 5.623     ,  8.992     ,  8.81333333,  7.101     ,  6.943     ],
       [ 9.806     ,  5.67166667,  3.702     ,  2.62125   ,  6.5845    ],
       [ 8.101     ,  3.81533333,  6.42333333,  2.0555    ,  2.822     ],
       [ 8.127     ,  5.70433333,  6.85566667,  7.7945    ,  4.4785    ],
       [ 4.121     ,  9.45066667,  7.95366667,  9.301     ,  7.5015    ],
       [10.        ,  3.618     ,  4.07466667,  2.3945    ,  4.55      ],
       [ 8.432     ,  3.24633333,  3.59833333,  3.19875   ,  2.579     ],
       [ 5.61      ,  8.671     ,  6.67733333,  8.58375   ,  7.562     ],
       [ 4.934     ,  8.83666667,  8.329     ,  7.08675   ,  8.2805    ],
       [ 8.546     ,  5.384     ,  6.01033333,  4.88325   ,  7.387     ],
       [ 3.698     ,  8.27933333,  8.549     ,  6.787     ,  4.484     ],
       [ 9.289     ,  5.59633333,  5.51066667,  7.04825   ,  7.4215    ],
       [ 7.618     ,  6.18866667,  6.752     ,  6.2       ,  6.4325    ],
       [ 3.489     ,  9.72466667,  7.68266667,  7.95425   ,  6.495     ],
       [ 5.189     ,  6.18966667,  8.57766667,  5.46025   ,  7.618     ],
       [ 7.926     ,  6.21266667,  8.09666667,  6.05525   ,  8.055     ],
       [ 5.363     ,  8.992     ,  8.63366667,  5.922     ,  7.214     ],
       [ 6.032     ,  8.671     ,  5.78633333,  4.04675   ,  3.678     ],
       [ 9.544     ,  4.34266667,  5.31233333,  2.9425    ,  4.2225    ],
       [ 3.411     ,  7.85666667,  8.22033333,  8.57625   ,  8.8045    ],
       [ 3.141     ,  8.671     ,  6.06033333,  9.272     ,  7.093     ],
       [ 4.37      ,  6.79      ,  8.338     ,  6.02675   ,  5.516     ],
       [ 5.125     ,  8.83666667,  8.55933333,  8.805     ,  9.3425    ],
       [ 6.183     ,  7.40833333,  7.43366667,  3.94175   ,  5.0625    ],
       [ 9.82      ,  1.        ,  4.17833333,  2.2725    ,  4.5505    ],
       [ 7.806     ,  6.104     ,  6.08566667,  3.35125   ,  2.909     ]])

In [16]:
column2 = sekector.get_feature_names_out()
column2

array(['Cost of Living', 'Business Freedom', 'Healthcare',
       'Environmental Quality', 'Tolerance'], dtype=object)

In [17]:
train_x_new = train_x[column2]
test_x_new = test_x[column2]
reg = LinearRegression().fit(train_x_new, train_y)
predictions = reg.predict(test_x_new)
Ri = r2_score(test_y, predictions)
MSE = mean_squared_error(test_y, predictions)
print("Новая модель: Rквадрат:", Ri, "MSE:", MSE)

Новая модель: Rквадрат: 0.8134291249967048 MSE: 234.5536270852422

Модель стала лучше, то отличается (в худшую сторону) в отличие от первого

In [18]:
#Сделаем полиномиальные признаки
from sklearn.preprocessing import PolynomialFeatures
poly = PolynomialFeatures(2)
train_X_poly = pd.DataFrame(poly.fit_transform(train_x), columns=poly.get_feature_names_out())
test_X_poly = pd.DataFrame(poly.fit_transform(test_x), columns=poly.get_feature_names_out())

In [19]:
reg = LinearRegression().fit(train_X_poly, train_y)
predictions = reg.predict(test_X_poly)
Ri = r2_score(test_y, predictions)
MSE = mean_squared_error(test_y, predictions)
print("Исходная модель: Rквадрат:", Ri, "MSE:", MSE)

Исходная модель: Rквадрат: -0.44844337203832807 MSE: 1820.9575665717834

In [29]:
from sklearn.feature_selection import f_regression, SelectKBest
f_statistic, p_values = f_regression(train_X_poly, train_y)
sekector = SelectKBest(f_regression, k=20)
sekector.fit_transform(train_X_poly, train_y)

C:\Users\nelli\anaconda3\lib\site-packages\sklearn\feature_selection\_univariate_selection.py:289: RuntimeWarning: divide by zero encountered in true_divide
  correlation_coefficient /= X_norms
C:\Users\nelli\anaconda3\lib\site-packages\sklearn\feature_selection\_univariate_selection.py:358: RuntimeWarning: invalid value encountered in true_divide
  f_statistic = corr_coef_squared / (1 - corr_coef_squared) * deg_of_freedom
C:\Users\nelli\anaconda3\lib\site-packages\sklearn\feature_selection\_univariate_selection.py:289: RuntimeWarning: divide by zero encountered in true_divide
  correlation_coefficient /= X_norms
C:\Users\nelli\anaconda3\lib\site-packages\sklearn\feature_selection\_univariate_selection.py:358: RuntimeWarning: invalid value encountered in true_divide
  f_statistic = corr_coef_squared / (1 - corr_coef_squared) * deg_of_freedom

array([[ 8.966     ,  8.17575   , 26.898     , ..., 37.6902075 ,
        64.79690662, 46.28888275],
       [ 8.671     ,  7.2505    , 26.013     , ..., 39.70736325,
        34.62476275, 31.10999475],
       [ 7.43866667,  3.672     , 14.87733333, ...,  9.747324  ,
        27.560196  , 22.48272525],
       ...,
       [ 7.40833333,  3.94175   ,  7.40833333, ..., 12.79097875,
        19.95510937, 47.536875  ],
       [ 1.        ,  2.2725    ,  5.        , ...,  3.73030875,
        10.34101125,  9.000889  ],
       [ 6.104     ,  3.35125   ,  6.104     , ..., 13.8406625 ,
         9.74878625, 20.485178  ]])

In [30]:
column3 = sekector.get_feature_names_out()
column3

array(['Business Freedom', 'Environmental Quality',
       'UA_Continent Business Freedom',
       'UA_Continent Environmental Quality', 'Cost of Living^2',
       'Commute Environmental Quality', 'Business Freedom^2',
       'Business Freedom Healthcare',
       'Business Freedom Environmental Quality',
       'Business Freedom Economy', 'Business Freedom Internet Access',
       'Business Freedom Tolerance', 'Healthcare Environmental Quality',
       'Healthcare Economy', 'Education Environmental Quality',
       'Environmental Quality^2', 'Environmental Quality Economy',
       'Environmental Quality Internet Access',
       'Environmental Quality Tolerance', 'Economy Tolerance'],
      dtype=object)

In [31]:
train_X_new = train_X_poly[column3]
test_X_new = test_X_poly[column3]
reg = LinearRegression().fit(train_X_new, train_y)
predictions = reg.predict(test_X_new)
Ri = r2_score(test_y, predictions)
MSE = mean_squared_error(test_y, predictions)
print("Новая модель: Rквадрат:", Ri, "MSE:", MSE)

Новая модель: Rквадрат: 0.7411937133321633 MSE: 325.3667178724005